### ISSUE TITLE
Change name of LiDET_fMET

### ISSUE THREAD

**Issue by wwieder** [piersond/MIMICS_STODE#9]
I might change the name of the `LiDET_fMET` to something like `fixed_fMET` to clarify what this logical flag is really doing.

https://github.com/piersond/MIMICS_STODE/blob/64bf9cc4ad51385f4b203d8f19c9864fc313cc93/calc_Tpars.R#L15C61-L15C61

**Comment by wwieder** [comment]
This also has to be changed in places like MIMICS_steady_state_pools.R where you're calling calc_Tpars_Conly

**Comment by piersond** [comment]
"LiDET_fMET" is no longer found in the code. Marking this issue resolved.
